#!/usr/bin/env bash
# script to check if all websites is working

check_dom () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    check_dom "$2.$1" "$2"
else
    check_dom "www.$1" "www"
    check_dom "lb-01.$1" "lb-01"
    check_dom "web-01.$1" "web-01"
    check_dom "web-02.$1" "web-02"
fi
