#!/usr/bin/env bash
# This script configures Nginx on a server
# Configs: listen on port 80 & return 'Hello World!' at /
apt-get update -y; apt-get install nginx -y; echo "Hello World!" > /var/ww//html/index.nginx-debian.html; service nginx restart
