#!/usr/bin/env bash
# a Bash script containing commands to automatically configure a Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location / {
        add_header X-Served-By \$hostname;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html/;
        internal;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
