#!/usr/bin/env bash
# Write a Bash script that:
mkdir var/
cd var/
mkdir run/
cd run/
touch myscript.pid

i=1
while [ "$i" -eq 1 ]
do
    echo "To infinity and beyond"
    sleep 2
done

trap "echo 'I hate the kill command'; sudo rm /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "sudo rm /var/run/myscript.pid; exit" SIGQUIT