#!usr/bin/env bash
# Let’s install the ufw firewall and setup a few rules on web-01 and web-02 and lb-01

sudo apt update -y;
sudo apt install ufw;
sudo ufw status;
sudo ufw default deny incoming;
sudo ufw default allow outgoing;
sudo ufw enable -y;
sudo ufw allow 22;
sudo ufw allow 443;
sudo ufw allow 80;
sudo ufw status;
